spring.application.name=smartcontactmanager

spring.datasource.url = jdbc:postgresql://localhost:5432/mydb
spring.datasource.username = your username
spring.datasource.password = your password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto = update
spring.servlet.multipart.max-file-size = -1
spring.servlet.multipart.max-request-size = -1


